name: Build and Test Flink Jobs

on:
  push:
    branches: [ main ]
    paths:
      - 'flink-jobs/**'
      - '.github/workflows/flink-jobs-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'flink-jobs/**'
      - '.github/workflows/flink-jobs-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew flink-jobs:build

      - name: Run tests
        run: ./gradlew flink-jobs:test

      - name: Build Shadow JAR
        run: ./gradlew flink-jobs:shadowJar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flink-jobs-jar
          path: flink-jobs/build/libs/flink-jobs-*.jar