name: Build and Test Generator

on:
  push:
    branches: [ main ]
    paths:
      - 'generator/**'
      - '.github/workflows/generator-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'generator/**'
      - '.github/workflows/generator-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew generator:build

      - name: Run tests
        run: ./gradlew generator:test

      - name: Build Shadow JAR
        run: ./gradlew generator:shadowJar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generator-jar
          path: generator/build/libs/generator-*.jar