name: Validate Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Initialize Kafka for KRaft mode
        run: |
          docker compose up --exit-code-from kafka-init kafka-init

      - name: Start services
        run: docker compose up -d

      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka to be ready..."
          timeout=180
          elapsed=0
          interval=10

          until docker compose exec -T kafka kafka-topics --bootstrap-server kafka:9092 --list > /dev/null 2>&1 || [ $elapsed -ge $timeout ]; do
            echo "Kafka not ready yet, waiting... ($elapsed/$timeout seconds)"
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for Kafka to be ready"
            docker compose logs kafka
            exit 1
          fi

          echo "Kafka is ready!"

      - name: Wait for Trino to be ready
        run: |
          echo "Waiting for Trino to be ready..."
          timeout=180
          elapsed=0
          interval=10

          until docker compose exec -T trino-coordinator trino --execute "SELECT 1" > /dev/null 2>&1 || [ $elapsed -ge $timeout ]; do
            echo "Trino not ready yet, waiting... ($elapsed/$timeout seconds)"
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for Trino to be ready"
            docker compose logs trino-coordinator
            exit 1
          fi

          echo "Trino is ready!"

      - name: Check service status
        run: docker compose ps

      - name: Validate Trino
        run: |
          chmod +x scripts/validate-trino.sh
          ./scripts/validate-trino.sh

      - name: Check Kafka topics
        run: docker compose exec -T kafka kafka-topics --bootstrap-server kafka:9092 --list

      - name: Stop services
        if: always()
        run: docker compose down
